### ISSUE TITLE
Verified?

### ISSUE THREAD

**Issue by averms** [flathub/org.bunkus.mkvtoolnix-gui#20]
Is this flatpak officially supported by upstream? If so, it would be great if it was [verified on Flathub](https://flathub.org/about). If not feel free to close.

**Comment by mbunkus** [comment]
It is. Unfortunately the verification process seems to be broken at the moment. When I go to the app's developer settings & click on the "Begin" button, the browser console shows an error:

```
POST https://flathub.org/api/v2/verification/org.bunkus.mkvtoolnix-gui/setup-website-verification?new_app=undefined 422
```

Oh well… I'll try again in a couple of days.

**Comment by mbunkus** [comment]
After posting about the issue a Flathub developer fixed it within a couple of hours, which I highly appreciate. It's verified now.

Thanks for bringing verification to my attention. I didn't know about that feature.
