### ISSUE TITLE
Info: runtime org.kde.Platform branch 6.6 is end-of-life

### ISSUE THREAD

**Issue by DjDiabolik** [flathub/org.bunkus.mkvtoolnix-gui#35]
It's appear this warning when try to upgrade the flathub app...

https://discourse.flathub.org/t/org-kde-platform-branch-6-6-is-end-of-life-need-to-update-manually/8047

Apparently you have need to update this app directly.... thanks in advance :)

**Comment by privacyadmin** [comment]
+1 to this issue as well.

Temporarily uninstalled MKVToolnix for now.

Thank you for your help in support flapaks!
