### ISSUE TITLE
No filters in Add files dialog under KDE

### ISSUE THREAD

**Issue by eszlari** [flathub/org.bunkus.mkvtoolnix-gui#5]
https://bugs.kde.org/show_bug.cgi?id=427306

**Comment by mbunkus** [comment]
Is this a bug in KDE? In the FlatPak runtime? In MKVToolNix (that's the only thing I could fix)? For what it's worth, the dialog does have filters when running a normally-compiled MKVToolNix GUI under regular KDE Plasma 5.19.4 + Qt 5.15.0 on Arch (my main development machine).

**Comment by eszlari** [comment]
I guess it's a bug in `xdg-desktop-portal-kde`, since the flatpak works under GNOME, see bug report.

**Comment by mbunkus** [comment]
Thanks. I did read the bug report prior to asking, but I simply don't know enough about how FlatPak works to be sure what it meant.

**Comment by eszlari** [comment]
https://docs.flatpak.org/en/latest/desktop-integration.html#portals

**Comment by mbunkus** [comment]
Works fine at the moment. Closing.
