### ISSUE TITLE
host filesystem permission should be removed

### ISSUE THREAD

**Issue by laurinneff** [flathub/org.bunkus.mkvtoolnix-gui#7]
Qt/KDE uses XDG desktop portals, so unless I'm missing something, the host fs permission isn't actually needed

**Comment by mbunkus** [comment]
The programs actually doing the work (`mkvmerge` etc.) don't use Qt for accessing files. They also access files that the user hasn't chosen explicitly via a file selector (portal), e.g. when processing Blu-rays or DVDs.

**Comment by laurinneff** [comment]
Oh I see, thanks, that makes sense
