### ISSUE TITLE
Hangs when trying to add a file

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/org.bunkus.mkvtoolnix-gui#8]
When I try to add files the app stops responding and I have to kill the process.
```
flatpak run org.bunkus.mkvtoolnix-gui 
F: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs on /run/user/500/doc: File exists
Gtk-Message: 20:06:47.885: Failed to load module "xapp-gtk3-module"
Qt: Session management error: Could not open network socket
startNextAutoJob numRunning 0 toStart QVector()
cleanupAtEndOfQueue
```

**Comment by mbunkus** [comment]
Cannot reproduce; works fine on my end. Sounds like either an issue with your system or with the file in question. If you can reproduce the issue with the same file(s) with either a self-compiled version or a traditionally packaged one, please re-file this on my [actual issue tracker](https://gitlab.com/mbunkus/mkvtoolnix/-/issues). I'll also need access to the file in that case; please see [here](https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/FTP-server) for a place to upload it. Thanks.
