### ISSUE TITLE
Program hangs when trying to choose a target path on a remote filesystem

### ISSUE THREAD

**Issue by hzulla** [flathub/org.bunkus.mkvtoolnix-gui#9]
This happened with Ubuntu 22.04 and mkvtoolnix installed via flatpak.

- Mounted my home NAS fileserver with sftp://username@nas/ using Ubuntu's Nautilus file explorer.
- Three source files (one video, two .srt subtitle files) stored on the computer's local filesystem
- Prepared to multiplex them into one mkv file via mkvtoolnix-gui
- Chose a writable directory on the remote filesystem as the target directory and a filename for the resulting file
- After returning from the target file chooser dialog back to mkvtoolnix-gui, the application hangs
- no response to mouse clicks
- can't start multiplexing
- had to kill the mkvtoolnix-gui application via the command line

Same process worked fine when using a target on the computer's local filesystem and _then_ copying the result file to the remote filesystem via Nautilus.

**Comment by mbunkus** [comment]
I don't think this is something I can help you with (which is why I haven't replied earlier, simply had no idea what to say to this type of issue). Closing.
